### ISSUE TITLE
Ошибка: Failed at the bem-ide@0.0.1 postinstall script.

### ISSUE THREAD

**Issue by aravil** [belyanskii/bem-ide#12]
Ubuntu 14.04

	user@host:~/bem-ide$ npm i
	npm WARN deprecated enb-bem@0.1.0-beta2: Use `enb-bem-techs` instead.
	|
	> bem-ide@0.0.1 postinstall /home/ra/bem-ide
	> bower-npm-install --non-interactive

	bower not-cached    git://github.com/bem/bem-mvc.git#v2
	bower resolve       git://github.com/bem/bem-mvc.git#v2
	bower not-cached    git://github.com/bem/bem-components.git#a02b09448af2c292d8a628e0344d7cd97cb9867e
	bower resolve       git://github.com/bem/bem-components.git#a02b09448af2c292d8a628e0344d7cd97cb9867e
	bower not-cached    git://github.com/bem/bem-core.git#v2.5.0
	bower resolve       git://github.com/bem/bem-core.git#v2.5.0
	bower checkout      bem-components#a02b09448af2c292d8a628e0344d7cd97cb9867e
	bower checkout      bem-mvc#v2
	bower download      https://github.com/bem/bem-core/archive/v2.5.0.tar.gz
	bower invalid-meta  bem-mvc is missing "main" entry in bower.json
	bower resolved      git://github.com/bem/bem-mvc.git#62db73e859
	bower cached        git://github.com/bem/bem-components.git#2.0.0
	bower validate      2.0.0 against git://github.com/bem/bem-components.git#v2
	bower extract       bem-core#v2.5.0 archive.tar.gz
	bower new           version for git://github.com/bem/bem-components.git#v2
	bower resolve       git://github.com/bem/bem-components.git#v2
	bower not-cached    git://github.com/narqo/bem-pr.git#~0.5.0
	bower resolve       git://github.com/narqo/bem-pr.git#~0.5.0
	bower download      https://github.com/bem/bem-components/archive/v2.1.0.tar.gz
	bower download      https://github.com/narqo/bem-pr/archive/0.5.3.tar.gz
	bower progress      bem-components#a02b09448af2c292d8a628e0344d7cd97cb9867e Receiving objects:  53% (12536/23651), 4.15 MiB | 791.00 KiB/s
	bower extract       bem-pr#~0.5.0 archive.tar.gz
	bower progress      bem-components#a02b09448af2c292d8a628e0344d7cd97cb9867e Receiving objects:  59% (13955/23651), 4.93 MiB | 848.00 KiB/s
	bower invalid-meta  bem-core is missing "main" entry in bower.json
	bower progress      bem-components#a02b09448af2c292d8a628e0344d7cd97cb9867e Receiving objects:  76% (17975/23651), 5.82 MiB | 893.00 KiB/s
	bower invalid-meta  bem-pr is missing "main" entry in bower.json
	bower progress      bem-components#a02b09448af2c292d8a628e0344d7cd97cb9867e Resolving deltas:  12% (1104/9154)
	bower extract       bem-components#v2 archive.tar.gz
	bower resolved      git://github.com/narqo/bem-pr.git#0.5.3
	bower progress      bem-components#a02b09448af2c292d8a628e0344d7cd97cb9867e Resolving deltas:  94% (8611/9154)
	bower resolved      git://github.com/bem/bem-core.git#2.5.0
	bower invalid-meta  bem-components is missing "main" entry in bower.json
	bower mismatch      Version declared in the json (2.0.0) is different than the resolved one (2.1.0)
	bower invalid-meta  bem-components is missing "main" entry in bower.json
	bower resolved      git://github.com/bem/bem-components.git#a02b09448a
	bower resolved      git://github.com/bem/bem-components.git#2.1.0
	bower not-cached    git://github.com/bem/bem-core.git#2.6.0
	bower resolve       git://github.com/bem/bem-core.git#2.6.0
	bower download      https://github.com/bem/bem-core/archive/v2.6.0.tar.gz
	bower extract       bem-core#2.6.0 archive.tar.gz
	bower invalid-meta  bem-core is missing "main" entry in bower.json
	bower resolved      git://github.com/bem/bem-core.git#2.6.0
	bower ECONFLICT     Unable to find suitable version for bem-core
	bower ECONFLICT     Unable to find suitable version for bem-core
	bem-core: Unable to find suitable version for bem-core
	    at createError (/home/ra/bem-ide/node_modules/bower/lib/util/createError.js:4:15)
	    at Manager._electSuitable (/home/ra/bem-ide/node_modules/bower/lib/core/Manager.js:763:15)
	    at /home/ra/bem-ide/node_modules/bower/lib/core/Manager.js:558:25
	    at _fulfilled (/home/ra/bem-ide/node_modules/bower/node_modules/q/q.js:794:54)
	    at self.promiseDispatch.done (/home/ra/bem-ide/node_modules/bower/node_modules/q/q.js:823:30)
	    at Promise.promise.promiseDispatch (/home/ra/bem-ide/node_modules/bower/node_modules/q/q.js:756:13)
	    at /home/ra/bem-ide/node_modules/bower/node_modules/q/q.js:516:49
	    at flush (/home/ra/bem-ide/node_modules/bower/node_modules/q/q.js:110:17)
	    at process._tickCallback (node.js:448:13)

	npm ERR! bem-ide@0.0.1 postinstall: `bower-npm-install --non-interactive`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the bem-ide@0.0.1 postinstall script.
	npm ERR! This is most likely a problem with the bem-ide package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     bower-npm-install --non-interactive
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls bem-ide
	npm ERR! There is likely additional logging output above.
	npm ERR! System Linux 3.13.0-48-generic
	npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
	npm ERR! cwd /home/ra/bem-ide
	npm ERR! node -v v0.10.38
	npm ERR! npm -v 1.4.28
	npm ERR! code ELIFECYCLE
	npm ERR! 
	npm ERR! Additional logging details can be found in:
	npm ERR!     /home/ra/bem-ide/npm-debug.log
	npm ERR! not ok code 0

**Comment by trebushuk** [comment]
Ubuntu 14.04
npm -v //-> 1.4.9
node -v //-> v0.10.25
```
% npm i
> bem-ide@0.0.1 postinstall /home/vladimir/Workspace/bem-ide
> bower-npm-install --non-interactive

npm ERR! peerinvalid The package enb does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer enb-bem@0.1.0-beta2 wants enb@>= 0.13.0 < 1.0.0
npm ERR! peerinvalid Peer enb-bemxjst@1.3.5 wants enb@>= 0.13.0 < 1.0.0
npm ERR! peerinvalid Peer enb-borschik@1.6.0-beta1 wants enb@>= 0.16.0 < 1.0.0
npm ERR! peerinvalid Peer enb-diverse-js@0.1.0 wants enb@>= 0.8.22
npm ERR! peerinvalid Peer enb-modules@0.2.0 wants enb@>= 0.8.22

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/vladimir/Workspace/bem-ide
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.9
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vladimir/Workspace/bem-ide/npm-debug.log
npm ERR! not ok code 0
```
